### ISSUE TITLE
SwerveModule is not a Subsystem

### ISSUE THREAD

**Issue by smtopps** [HoyaRobotics/2023ChargedUp#1]
https://github.com/HoyaRobotics/2023ChargedUp/blob/65f1031f93ac02b6b6be98a65dd1a3f79fa5977b/src/main/java/frc/robot/subsystems/SwerveModule.java#L26
SwerveModule is a custom class and not a subsystem so you want to get rid of `extends SubsystemBase `.

https://github.com/HoyaRobotics/2023ChargedUp/blob/65f1031f93ac02b6b6be98a65dd1a3f79fa5977b/src/main/java/frc/robot/subsystems/SwerveModule.java#L19
This line will then need to be removed as it should be a useless import.

**Comment by Williamzammit** [comment]
Fixed
